# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn package -Pnative -Dquarkus.native.container-build=true
    - name: Upload build artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        path: ./target/*-runner
        if-no-files-found: error
    - name: Push to Github packages
      uses: docker/build-push-action@v1.1.0
      with: 
        username: joern19
        password: ${{ secrets.KEY_GITHUB }}
        registry: docker.pkg.github.com
        dockerfile: ./src/main/docker/Dockerfile.native
        cache_froms: registry.access.redhat.com/ubi8/ubi-minimal:8.1
        repository: docker.pkg.github.com/joern19/easter_egg_counter/quarkus-counter
        tags: latest
